### ISSUE TITLE
Separate server 

### ISSUE THREAD

**Issue by shujaatak** [apinprastya/sultan#21]
It would be great to have a separate server program rather than mixed with Client. It can be a simple console app handling only database.

**Comment by shujaatak** [comment]
OR
If you want to keep it like the way it is then can you please give me some hints how can I separate server from the rest of the code for my use case?

**Comment by apinprastya** [comment]
It is interesting, it can be done in 2 ways : 

1. Fully console application : it will be separated server application with no GUI at all. Setting can be done from file (like setting.json) for the database setting and other server setting. This need to remove completely GUI library call.
2. Current application but able to start without GUI. So by calling something like "Sultan --no-gui" will start the Sultan without GUI. This will be less work compare to number 1, but the application still linked to GUI even the GUI is not used.

I am not sure which one is the most suitable. In the real live, it is good to keep the current (server + client in 1 app) because we can use the the server also to do any editing prices, purchases, etc. Using 1 dedicated server without able to act as client is something wasting resources, unless we have big minimarket.

**Comment by shujaatak** [comment]
I think the first way is more flexible because it allows the user to either install both client and server on one computer or on separate computers according to his/her use case.

**Comment by apinprastya** [comment]
Implemented e35b48e90e18431945b5bfe99a36e1d1e46ba273
Only checked on Linux, no time to check on windows.
I think this is a good feature, now the Sultan server able to run on cloud.

**Comment by shujaatak** [comment]
I will test it as soon as possible!
