### ISSUE TITLE
I can't choose between WebEngine and WebKit

### ISSUE THREAD

**Issue by shujaatak** [apinprastya/sultan#5]
I am trying to build the project in Windows 10, Qt 5.9.

When i try to build the project with  `CONFIG   += USE_WEBENGINE` then I get this error: `Project ERROR: Unknown module(s) in QT: webenginewidgets`. 
But if i don't use  `CONFIG   += USE_WEBENGINE` then I get this error: `Project ERROR: Unknown module(s) in QT: webkitwidgets`

For me the sultan has just stopped working.

I think you should use `QT += webengine` rather than `QT += webenginewidgets`

**Comment by apinprastya** [comment]
Webkit was removed since Qt 5.6 from the binary distribution. Webengine not available on Qt MinGW.
If you want to use webkit : 
1. Use Qt 5.5
2. Build the webkit module on your own
If you want to use webengine : 
1. Install Qt 5.9 with MVC 2015 as compiler

And for note, I will release next version for Windows with Qt 5.5 and it will use webkit.

**Comment by shujaatak** [comment]
So this means I should stop using Qt 5.9 MinGW and move to Qt 5.9 with MVC 2015. I have no intention to move back to Qt 5.5.
